# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-25 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20190201_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 20, 41, 15, 607000), verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
    ]
