# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-20 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20190225_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='\u4f5c\u8005ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 20, 36, 27, 559000), verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
    ]
