# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_path', models.FilePathField(verbose_name='\u56fe\u8868\u8def\u5f84')),
                ('img_name', models.CharField(max_length=30, verbose_name='\u56fe\u8868\u540d\u79f0')),
            ],
        ),
    ]
