# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 02:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u4fe1\u606f\u552f\u4e00ID')),
                ('words', models.TextField(verbose_name='\u7559\u8a00\u5185\u5bb9')),
                ('public_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7559\u8a00\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'ordering': ['public_time'],
                'verbose_name': '\u7528\u6237\u7559\u8a00\u8868',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00\u8868',
            },
        ),
    ]
