# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False),
        ),
    ]
