# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False, unique=True, verbose_name='\u89c6\u9891ID')),
                ('url', models.CharField(default='', max_length=100, verbose_name='\u89c6\u9891\u5730\u5740')),
                ('title', models.CharField(default='', max_length=300, verbose_name='\u89c6\u9891\u6807\u9898')),
                ('types', models.CharField(default='\u52a8\u6f2b', max_length=100, verbose_name='\u89c6\u9891\u7c7b\u578b')),
                ('public_time', models.DateTimeField(default=datetime.datetime(2019, 2, 1, 10, 53, 34, 449000), verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author_name', models.CharField(default='\u672a\u77e5', max_length=300, verbose_name='\u4f5c\u8005\u6635\u79f0')),
                ('author_url', models.CharField(default='', max_length=100, verbose_name='\u4f5c\u8005\u4e3b\u9875')),
                ('view', models.IntegerField(default=0, verbose_name='\u64ad\u653e\u6570\u91cf')),
                ('danmaku', models.IntegerField(default=0, verbose_name='\u5f39\u5e55\u6570\u91cf')),
                ('reply', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('favorite', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570\u91cf')),
                ('coin', models.IntegerField(default=0, verbose_name='\u786c\u5e01\u6570\u91cf')),
                ('share', models.IntegerField(default=0, verbose_name='\u5206\u4eab\u6570\u91cf')),
                ('like', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570\u91cf')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author', verbose_name='\u4f5c\u8005ID')),
            ],
            options={
                'ordering': ['public_time'],
                'verbose_name': '\u89c6\u9891\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u89c6\u9891\u4fe1\u606f\u8868',
            },
        ),
    ]
