# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='public_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 10, 59, 20, 609000), verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
