# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-25 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190201_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='public_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 20, 41, 15, 609000), verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
