# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-20 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190225_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='view',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='\u89c6\u9891ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='public_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 20, 36, 27, 561000), verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
